### ISSUE TITLE
Redirect after inviting player.

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#10]
Inviting player to team doesn't redirect back to team after sending invite.

Select Team > Invite Players > Select Player > Invite

After pressing invite on the player it stays on their bio instead of redirecting back to the team page.

**Comment by donlafranchi** [comment]
@Igonato: This looks good to me.  We can close this one unless you have something else you need to do on this.

**Comment by Igonato** [comment]
@mrlafranchi feel free to close issues that are done. There are bunch of them in the Review/QA pipeline.
