### ISSUE TITLE
Redirect on Save for Creating a New Game

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#16]
After user creates a new game and saves: 
User is redirected back to "Create a game" details view when clicking back button.  Instead user should just be directed back to Team Schedule Tab

**Comment by bsko** [comment]
https://github.com/goodfootclub/web/pull/54

**Comment by bsko** [comment]
Well, its fixed but:
Its not that easy to open exact tab. Is it critical?

**Comment by donlafranchi** [comment]
It's not critical.
