### ISSUE TITLE
Sign up with email

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#2]
Currently the only way to sign up is through email.

**Comment by Igonato** [comment]
The API is ready: https://dev.goodfoot.club/api/#!/auth/register_create

Front end work needed:
- [ ] Sign up form
- [ ] Activate view (ping me to adjust the url that gets sent in the email)
- [ ]  Password reset view (... same ...)

**Comment by bsko** [comment]
https://github.com/goodfootclub/web/pull/61

**Comment by bsko** [comment]
Hmm.. password reset? We need it too?
