### ISSUE TITLE
Capture email address for players

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#34]

**Comment by Igonato** [comment]
@mrlafranchi Yo. I forgot what this one is about. Can you add description?

**Comment by donlafranchi** [comment]
Let's collect everyone's email addresses. We haven't yet so we have no way of communicating with people. This way we can send emails for invites and game reminders and new pickup games.

**Comment by Igonato** [comment]
We're getting it from Facebook. So it's taken care off
