### ISSUE TITLE
Teams related bugs!

### ISSUE THREAD

**Issue by bsko** [goodfootclub/specs#38]
1) /teams/my/ doesnt return teams where i'm a manager! Its very uncomortable to search for my teams in all-teams-view, searching by team name

2) If i am a manager - i can invite myself as a player. And i will need to approve this invitation on invitations view.

3) If i'm trying to invite a person to a team that has games scheduled- im getting error:

detail: Ensure that the change is withing the following options: - User joins pickup games and asks to join league games - Player changes status or leaves - Game organizer removes player from open games - Team manager can invite and remove players to/from league games

request:
Request URL:https://dev.goodfoot.club/api/games/463/players/
Request Method:POST
Status Code:403 Forbidden
{
  "id": 259,
  "rsvp": -1,
  "team": 0
}

**Comment by Igonato** [comment]
> /teams/my/ doesnt return teams where i'm a manager!

I made a separate endpoint for managed teams. /teams/managed/

Work in progress on the rest

**Comment by bsko** [comment]
1) refactored my-teams view to show teams in 2 tabs : as a manager and as a player.
Please fix invites counter in a response from /api/users/me/

**Comment by Igonato** [comment]
Fixed 2. 3 in progress. I think I need to improve the error messages

**Comment by Igonato** [comment]
Didn't mean to close it just yet...
