### ISSUE TITLE
Name for Pickup Games

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#43]
Let's add a name or other identifier to a pickup game item.  Then they can be searchable.

**Comment by bsko** [comment]
You mean user should specify a name for a game to create it ?
On https://dev.goodfoot.club/games/add view ?

**Comment by donlafranchi** [comment]
Right. I guess @igonato needs to update the api first huh? And more importantly it was as a workaround since we haven't yet figured out how to direct someone to a specific game if they haven't signed in yet.

**Comment by bsko** [comment]
Agree.
@Igonato , we need:
1) add 'name' attribute to games.
2) fix games search http://localhost:4200/api/games/?limit=50&search=XXX to use 'name' attribute
3) add this 'name' to Game object in response from:
/api/games/
/api/games/my
/api/games/:id
/api/games/invites
&& handle it on /api/games/ POST

**Comment by Igonato** [comment]
Ok. On it

**Comment by Igonato** [comment]
API is done for this one
