### ISSUE TITLE
Label Pickup Game Creator

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#44]
If only the pickup game creator can invite players then they should be able to see which pickup games they have created (like their name shows up in the game list tile 'Created By: Aleksey'.  

Ideally anyone should be able to invite anyone to a pickup game.  Perhaps there should be a checkbox for pickup games that are not open to everyone.  Private Invite Only: Y

**Comment by bsko** [comment]
@Igonato , remove rights check pls. Currently, im not able to invite to a game, where i'm not an organizer:

Request URL:http://localhost:4200/api/games/484/players/
Request Method:POST
Status Code:403 Forbidden

**Comment by bsko** [comment]
@Igonato , lets discuss it. I think it makes sense to separate "public" and "private" games. Also, please add game organizer name to every game in response for list forms.

**Comment by bsko** [comment]
I will add organizer name on game details view.

**Comment by donlafranchi** [comment]
Can I get an update on this?
