### ISSUE TITLE
Open invitation for pickup game

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#45]
Anyone should be able to invite anyone to a pickup game for now.  

When we grow larger then we can limit who can invite whom to a pickup game. 

One idea is only those who've been invited can invite others.  For now though I'd like more open access to everyone.

**Comment by bsko** [comment]
@Igonato , remove rights check pls. Currently, im not able to invite to a game, where i'm not an organizer:

Request URL:http://localhost:4200/api/games/484/players/
Request Method:POST
Status Code:403 Forbidden

**Comment by Igonato** [comment]
Let's count this as a part of #44
