### ISSUE TITLE
Time Scheduling Bug

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#51]
If I create a game to begin at 10pm the game time is saved as 3pm (-7 hours).  My time zone is also -7 from UTC.

**Comment by bsko** [comment]
checking...

**Comment by Igonato** [comment]
I suspect it has something to do with mobile. I've got my hands on iPhone 4s, but it refuses to work at all (stuck at the home screen loading). Looking into it

**Comment by donlafranchi** [comment]
Are there any updates on this issue?

**Comment by bsko** [comment]
fixed
