### ISSUE TITLE
Game edit

### ISSUE THREAD

**Issue by Igonato** [goodfootclub/specs#52]
We should support editing games. If game time changes for example. Or location. This should be supported by the api at this moment.

**Comment by donlafranchi** [comment]
@bsko is there something you are still waiting on for this feature?

**Comment by bsko** [comment]
There is an issue to add Game name. Would be nice to implement it first. But rest endpoint is not working fine now, always saving 'null' in game name field. It should be fixed. Game-edit is implemented by ~80%. Waiting for working endpoints.
