### ISSUE TITLE
Delete Account/Profile

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#55]
Users need to be able to delete their account/profile.

**Comment by donlafranchi** [comment]
This is urgent since I'm asking people to check out our app on upwork.com. Please work on this asap.

**Comment by Igonato** [comment]
Added support on the back end. Ready to push once the DNS are back up

**Comment by donlafranchi** [comment]
@bsko Let's move the button to the edit screen.  I can see accidentally pushing delete when they meant to choose edit.

**Comment by bsko** [comment]
done
