### ISSUE TITLE
Format Home Screen

### ISSUE THREAD

**Issue by donlafranchi** [goodfootclub/specs#7]

**Comment by Igonato** [comment]
![de5f07e85833a5e1828d793a8a29d2780c041a3219c677bc81 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/788609/24332707/4136f5ac-1254-11e7-94ab-2af763dd1f90.jpg)
Fitbit app interface for referense

**Comment by mrlafranchi** [comment]
![Uploading Image uploaded from iOS.jpg…]()

New home screen layout.

**Comment by donlafranchi** [comment]
![image uploaded from ios](https://cloud.githubusercontent.com/assets/9556816/24393783/464c599c-134e-11e7-8bc7-a9f51610bd74.jpg)

**Comment by donlafranchi** [comment]
My Games, My Profile, My Teams are the only critical elements for the push at this time.

**Comment by bsko** [comment]
Next thing to implement is: 
show different text if user has no games/teams
1) no games: show something like "Join Pickup games"
2) no teams: show something like "Join a team or create one"
3) if there are no upcoming matches - remove NEXT GAME tile
